#!/usr/bin/env bash

# Create the PID file
echo $$ > /var/run/myscript.pid

# Function to handle SIGTERM signal
terminate() {
  echo "I hate the kill command"
}

# Function to handle SIGINT signal
interrupt() {
  echo "Y U no love me?!"
}

# Function to handle SIGQUIT and SIGTERM signals
cleanup() {
  echo "Deleting PID file and terminating"
  rm /var/run/myscript.pid
  exit 0
}

# Register signal handlers
trap terminate SIGTERM
trap interrupt SIGINT
trap cleanup SIGQUIT SIGTERM

# Infinite loop
while true; do
  echo "To infinity and beyond"
  sleep 1
done

